remote_theme : pages-themes/minimal@v0.2.0
<html lang="en">
<head>
  <meta charset="UTF-8">
  Bhupendra Singh Kanyal
    body {
      background-color: #000000;
      color: #f1f1f1;
      font-family: Arial, sans-serif;
      margin: 0;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
    }
    main {
      flex: 1;
      padding: 2rem;
    }
    footer {
      background-color: #00000;
      color: #ccc;
      text-align: center;
      padding: 1rem 0;
      font-size: 1rem;
      border-top: 1px solid #333;
    }
  </style>
</head>
<body>
  <main>
    <!-- Your website content goes here -->
    <h1>Welcome to My Website</h1>
    <p>This site uses a dark theme.</p>
  </main>
  <footer>
    Copyright - BeBhupendra ( All Right Served )
  </footer>
</body>
</html>

